# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CycleStats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CycleStats
 
  pod 'Firebase/Core'
  pod ‘Firebase/Auth’
  pod ‘Firebase/Database’
  pod ‘Firebase/Storage’
  pod ‘Firebase/Messaging’
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftChart'
  pod 'SwiftKeychainWrapper'

  target 'CycleStatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CycleStatsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
